config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources 'users'
    resources 'recipes' do
    resources 'reviews'
  end


  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/sort' => 'ajax#get_recipes'
  get '/search' => 'ajax#get_recipes'
  #post '/search' => 'ajax#search'
  get '/tags/:name' => 'tags#show', as: :tag
  get '/ingredients/:name' => 'ingredients#show', as: :ingredient
  post '/recipe/:id/favorite' => 'recipes#favorite', as: :favorite

  get '/age' => 'sessions#age'


end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :user
  has_many :recipes_tags
  has_many :favorites
  has_many :tags, through: :recipes_tags
  has_many :amounts
  has_many :ingredients, through: :amounts
  has_many :reviews, dependent: :destroy
  mount_uploader :img_upload, ImageUploader
  accepts_nested_attributes_for :amounts
  accepts_nested_attributes_for :tags

  validates :name, presence: true
  validates :description, presence: true
  validates :steps, presence: true
  #validate :validate_ingredients

  def validate_ingredients
    if amounts.size < 1
      errors.add(:ingredients, "requires at least one ingredient")
    end
  end
### DISPLAY

  def servings
    serves = read_attribute(:servings)
    if serves == 6
      "6+"
    else
      serves ||= 1
    end
  end

  def print_tag_names
    arr = self.tags.map do |tag|
      tag.name
    end

    if !arr.empty?
      arr.join(", ")
    else
      ""
    end
  end

  def downcase_tags
    self.tags.map do |tag|
      tag.name.downcase
    end
  end

  def downcase_ingredients
    self.ingredients.map do |ingred|
      ingred.name.downcase
    end
  end

  def display_difficulty
    str = "#{self.difficulty}"
    case self.difficulty
      when 1
        str << "<span>No sweat</span>"
      when 2
        str << "<span>Easy</span>"
      when 3
        str << "<span>Medium</span>"
      when 4
        str << "<span>Hard</span>"
      when 5
        str << "<span>Experts Only</span>"
    end

    str
  end

### RECIPE FORM

  def tag_names=(tag_names)
    self.tags.clear
    tag_names.each do |tag_name|
      if tag_name != ""
        tag = Tag.find_or_create_by(name: tag_name)
        self.tags << tag
      end
    end

    self.save
  end

  def amounts_attributes= (amounts_attributes)
    self.amounts.clear
    amounts_attributes.values.each do |amounts_attributes_attribute|
      if !amounts_attributes_attribute["ingredient_attributes"].nil? && amounts_attributes_attribute["ingredient_attributes"]["name"] != ""
        quantity = amounts_attributes_attribute["quantity"]
        unit = amounts_attributes_attribute["unit"]
        amount = Amount.create(quantity: quantity, unit: unit)
        amount.ingredient_attributes = amounts_attributes_attribute["ingredient_attributes"]
        self.amounts << amount
      end
    end

    self.save
  end

### INDEX SORT
  def self.filter_tag(tag, recipes)
    recipes.select do |recipe|
      recipe.tags.detect { |r_tag| r_tag.name.downcase == tag.downcase }
    end

  end

  def self.filter_ingredients(ingredient, recipes)
    recipes.select do |recipe|
      recipe.ingredients.detect { |r_tag| r_tag.name.downcase == ingredient.downcase }
    end
  end

  def self.sort_by_ajax(recipes, sort, tag, ingredient, order)
    if tag != "" && !tag.nil?
      recipes = Recipe.filter_tag(tag, recipes)
    end

    if ingredient != "" && !ingredient.nil?
      recipes = Recipe.filter_ingredients(ingredient, recipes)
    end

    case sort
      when "date"
        if order == "default"
          recipes = Recipe.sort_by_date(recipes)
          recipes.reverse
        else
          Recipe.sort_by_date(recipes)
        end
      when "difficulty"
        if order == "default"
          Recipe.sort_by_difficulty(recipes)
        else
          recipes = Recipe.sort_by_difficulty(recipes)
          recipes.reverse
        end
      when "servings"
        if order == "default"
          Recipe.sort_by_servings(recipes)
        else
          recipes = Recipe.sort_by_servings(recipes)
          recipes.reverse
        end
      when "popularity"
        if order == "default"
          Recipe.sort_by_popularity(recipes)
        else
          recipes = Recipe.sort_by_popularity(recipes)
          recipes.reverse
        end
      else
        Recipe.all
    end
  end

  def self.sort_by_popularity(recipes)
   @sorted = recipes.sort_by do |recipe|
      recipe.favorites.count
    end
   @sorted.reverse
  end

  def self.sort_by_difficulty(recipes)
    @sorted = recipes.sort_by do |recipe|
      recipe.difficulty
    end
    @sorted
  end

  def self.sort_by_servings(recipes)
    @sorted = recipes.sort_by do |recipe|
      if recipe.servings != nil
        recipe.servings.to_i
      else
        1
      end
    end
    @sorted
  end

  def self.sort_by_date(recipes)
    @sorted = recipes.sort_by do |recipe|
      recipe.created_at
    end
    @sorted.reverse
  end

  def self.search(search)
    if search.present?
        Recipe.includes(:ingredients).includes(:tags).where('lower(ingredients.name) LIKE ? OR lower(tags.name) LIKE ? OR lower(recipes.name) LIKE ? OR lower(recipes.description) LIKE ?' , "%#{search.downcase}%", "%#{search.downcase}%", "%#{search.downcase}%", "%#{search.downcase}%").references(:ingredients).references(:tags).order("recipes.created_at DESC").distinct()
    else
      Recipe.all
    end
  end

### USER FAVORITES METHODS
  def update_favorites(user)
    user_favorited?(user) ? unfavorite(user) : favorite(user)
  end

  def favorites_message(user)
    if user_favorited?(user)
      "<span class='added'>Saved to your favorites.</span>".html_safe
    else
      "<span class='removed'>Removed from your favorites.</span>".html_safe
    end
  end

  def favorites_count(user)
    if user_favorited?(user)
      self.favorites.count
    else
      self.favorites.count
    end
  end

  def heart_class(user)
    if user_favorited?(user)
      "glyphicon glyphicon-heart red-heart"
    else
      "glyphicon glyphicon-heart grey-heart"
    end
  end

  def similar_recipes
    similar_ing = []
    similar_tag = []
    i = self.ingredients.ids
    t = self.tags.ids

    recipes = Amount.select('recipe_id', 'count(recipe_id) AS recipe_count').where("ingredient_id in (?)", i).group('recipe_id').having("COUNT(recipe_id) >= 2").order("recipe_count DESC").limit(3)
    tags = RecipesTag.select('recipe_id', 'count(recipe_id) AS recipe_count').where("tag_id in (?)", t).group('recipe_id').having("COUNT(recipe_id) >= 2").order("recipe_count DESC").limit(3)

    recipes.each do |r_id|
      similar_ing << Recipe.find(r_id.recipe_id) if r_id.recipe_id != self.id
    end
    tags.each do |t_id|
      similar_tag << Recipe.find(t_id.recipe_id) if t_id.recipe_id != self.id
    end

    [similar_ing, similar_tag]
  end

private
  def user_favorited?(user)
    self.favorites.where(user: user).any?
  end

  def favorite(user)
    self.favorites.create(user_id: user.id)
  end

  def unfavorite(user)
    self.favorites.find_by(user_id: user.id).destroy
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, except: [:new, :create]

  def new
    @recipe = Recipe.new
    @recipe.amounts.build
    @recipe.amounts.first.build_ingredient
    @blank_amount = Amount.new
    @blank_amount.ingredient = Ingredient.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = current_user.id
    @recipe.downcase_ingredients
    @recipe.downcase_tags
    if @recipe.save
      redirect_to recipe_path(@recipe)
    else
      str = ""
      @recipe.errors.full_messages.each { |error| str << "#{error}.<br>"}
      @blank_amount = Amount.new
      @blank_amount.ingredient = Ingredient.new
      flash[:danger] = str.html_safe
      render 'new'
      flash.clear
    end
  end

  def edit
    correct_user
    @blank_amount = Amount.new
    @blank_amount.ingredient = Ingredient.new
  end

  def update
    @recipe.user_id = current_user.id
    @recipe.downcase_ingredients
    @recipe.downcase_tags
    @recipe.amounts.clear
    @recipe.tags.clear

    if @recipe.update(recipe_params)
      redirect_to recipe_path(@recipe)
    else
      str = ""
      @recipe.errors.full_messages.each { |error| str << "#{error}.<br>"}
      flash[:danger] = str.html_safe
      redirect_to edit_recipe_path(@recipe)
    end
  end

  def show
    @reviews = @recipe.reviews
    @new_review = @recipe.reviews.new
  end

  def destroy
    correct_user
    @recipe.destroy
    redirect_to root_path
  end

  def favorite
    @recipe.update_favorites(current_user)
    render json: {heart: @recipe.heart_class(current_user), message: @recipe.favorites_message(current_user), recipe: @recipe.id, count: @recipe.favorites_count(current_user) }
  end


  private

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:name, :description, :tools, :steps, :difficulty, :img_url, :img_upload, :servings, amounts_attributes: [:id, :quantity, :unit, ingredient_attributes: [:name, :id]], :tag_names => [])
  end

  def correct_user
    @recipe = Recipe.find(params[:id])
    redirect_to(user_path(current_user)) unless current_user?(@recipe.user) || current_user.id < 4
  end

end

app/views/recipes/_form.html.erb
<script>
$(function() {
  $("#tagBox").tagging();

  var ingredient = [""
      <% Ingredient.all.each do |ingredient| %>
        , "<%= ingredient.name %>"
      <% end %>
    ];

  $(document).on('keydown.autocomplete', ".ingredient_input", function() {
      $(this).autocomplete({source: ingredient});
  });
});

function addIngredient(){
  var x = $('.blank-amount-ingredient-field')
  x.removeClass('blank-amount-ingredient-field');

  var num_amounts = parseInt($("#num_amounts").val());
  $("#num_amounts").val(num_amounts + 1);
  //update [X] and _X_
  var hiddenhtml = x.html().replace(/\[\d+\]/g, "["+(num_amounts + 1)+"]");
  hiddenhtml = hiddenhtml.replace(/_\d+_/g, "_"+(num_amounts + 1)+"_");
  $('#amounts-ingredients').append('<div class="blank-amount-ingredient-field">'
                                    + hiddenhtml
                                    + '</div>');

  return false;
}

function removeIngredient(element){
  var x = $(element).parent().parent();
  x.remove();
  var num_amounts = parseInt($("#num_amounts").val());
  $("#num_amounts").val(num_amounts);

  return false;
}
</script>

<%= form_for @recipe do |f| %>
   <fieldset>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </fieldset>
   <fieldset>
    <%= f.label :description %>
    <%= f.text_area :description%>
  </fieldset>
  <div style="clear: both;">
  <fieldset class="col-sm-3">
    <%= f.label :difficulty %>
    <%= f.select :difficulty, [1, 2, 3, 4, 5] %>
  </fieldset>
  <fieldset class="col-sm-3">
    <%= f.label :servings %>
    <%= f.select :servings, [[1,1],[2,2],[3,3],[4,4],[5,5],["6+",6]] %>
  </fieldset>
</div>
   <div class="amounts-ingredients">
     <fieldset id='amounts-ingredients'>
      <div class="col-sm-7">
        <label class="form-control-label" for="ingredient">Ingredient</label>
      </div>
      <div class="col-sm-2">
        <label class="form-control-label" for="quantity">Quantity</label>
      </div>
      <div class="col-sm-2">
        <label class="form-control-label" for="amount">Amount</label>
      </div>
      <div class="col-sm-1">
        <label>Add</label>
      </div>
      <%= render partial: 'ingredient_form', locals: {recipe: @recipe, blank_amount: @blank_amount} %>
    </fieldset>
    <input type="hidden" id="num_amounts" value="<%= @recipe.amounts.size %>">
  </div>
  <fieldset>
    <%= f.label :tags %>
    <div data-tags-input-name="recipe[tag_names]" id="tagBox"><%= @recipe.print_tag_names %></div>
  </fieldset>
  <fieldset>
    <%= f.label :steps %>
    <%= f.text_area :steps %>
  </fieldset>
  </fieldset>
    <%= f.label "Upload a photo" %>
    <%= f.file_field :img_upload %>
  <fieldset><br>
<span class="btn btn-primary"><%= f.submit %></span>
<% end %>

<script>
function getFile(){
      document.getElementById("upfile").click();
  }
</script>

app/views/recipes/_ingredient_form.html.erb
<% if !@recipe.amounts.empty? %>
  <% @recipe.amounts.each_with_index do |amount, index| %>
    <div class="amount-ingredient-field">
      <div class="col-sm-7">
        <input class="ingredient_input ui-autocomplete-input form-control" name="recipe[amounts_attributes][<%= index %>][ingredient_attributes][name]" id="recipe_amounts_attributes_<%= index %>_ingredient_attributes_name" type="text" value="<%= amount.ingredient.name %>"/>
      </div>

      <div class="col-sm-2">
        <input class="form-control" placeholder="Quantity" name="recipe[amounts_attributes][<%= index %>][quantity]" id="recipe_amounts_attributes_<%= index %>_quantity" type="text" value="<%= amount.quantity %>">
      </div>

      <div class="col-sm-2">
         <input class="form-control" placeholder="Unit" name="recipe[amounts_attributes][<%= index %>][unit]" id="recipe_amounts_attributes_<%= index %>_unit" type="text" value="<%= amount.unit %>">
      </div>
      <div class="col-sm-1">
        <% if index == 0 %>
        <a onclick="addIngredient(); return false;" class="btn btn-default add-ingredient"><span class="glyphicon glyphicon-plus"></span></a>
        <% else %>
          <a onclick="removeIngredient(this); return false;" class="btn btn-default add-ingredient"><span class="glyphicon glyphicon-minus"></span></a>
        <% end %>
       </div>
    </div>
  <% end %>

  <% index = @recipe.amounts.size %>
<% else %>
  <div class="amount-ingredient-field">
    <div class="col-sm-7">
      <input class="ingredient_input ui-autocomplete-input form-control" name="recipe[amounts_attributes][0][ingredient_attributes][name]" id="recipe_amounts_attributes_0_ingredient_attributes_name" type="text" value=""/>
    </div>

    <div class="col-sm-2">
      <input class="form-control" placeholder="Quantity" name="recipe[amounts_attributes][0][quantity]" id="recipe_amounts_attributes_0_quantity" type="text" value="">
    </div>

    <div class="col-sm-2">
       <input class="form-control" placeholder="Unit" name="recipe[amounts_attributes][0][unit]" id="recipe_amounts_attributes_0_unit" type="text" value="">
    </div>
    <div class="col-sm-1">
      <a onclick="addIngredient(); return false;" class="btn btn-default add-ingredient"><span class="glyphicon glyphicon-plus"></span></a>
     </div>
  </div>

  <% index = 1%>
<% end %>
<% amount = @blank_amount %>

<div class="blank-amount-ingredient-field">
  <div class="col-sm-7">
    <input class="ingredient_input ui-autocomplete-input form-control" name="recipe[amounts_attributes][<%= index %>][ingredient_attributes][name]" id="recipe_amounts_attributes_<%= index %>_ingredient_attributes_name" type="text" value="<%= amount.ingredient.name %>"/>
  </div>

  <div class="col-sm-2">
    <input class="form-control" placeholder="Quantity" name="recipe[amounts_attributes][<%= index %>][quantity]" id="recipe_amounts_attributes_<%= index %>_quantity" type="text">
  </div>

  <div class="col-sm-2">
     <input class="form-control" placeholder="Unit" name="recipe[amounts_attributes][<%= index %>][unit]" id="recipe_amounts_attributes_<%= index %>_unit" type="text">
  </div>
  <div class="col-sm-1">
    <a onclick="removeIngredient(this); return false;" class="btn btn-default add-ingredient"><span class="glyphicon glyphicon-minus"></span></a>
   </div>
</div>

app/views/recipes/_recipe_teaser.html.erb
<div class="recipe recipe-<%= the_recipe.id %> teaser col-sm-6 col-md-4">
  <div class="item">
    <%= link_to the_recipe do %>
        <div class="description active-state" >
          <h3><%= truncate(the_recipe.description, :length => 200, :separator => ' ') %></h3>
          <div class="difficulty"><span class="glyphicon glyphicon-signal" aria-hidden="true"></span>Difficulty <%= the_recipe.difficulty %></div>
          <div class="servings"><span class="glyphicon glyphicon-glass" aria-hidden="true"></span> Serves <% if the_recipe.servings %><%= the_recipe.servings %><% else %>1<% end %></div>
        </div>
  <div class="static-state">
        <% if the_recipe.img_upload.url %>
          <div class="thumbnail" style="background-image:url('<%= the_recipe.img_upload.url %>')">
            <%= image_tag the_recipe.img_upload.url, class: "thumbnail" %>
        <% else %>
          <div class="thumbnail">
            <div class="glass">
              <div class="water">
                <% the_recipe.amounts.each do |x| %>
                  <div style="background-color:#<%= "%06x" % (rand * 0xffffff) %>;height:<%= (1 / the_recipe.amounts.size.to_f) * 100 %>%"></div>
                <% end %>
              </div>
            </div>
        <% end %>

      </div>
      <div class="caption">
        <header>
          <h3><%= the_recipe.name %></h3>
        </header>
      </div>
    </div>
  <% end %>


    <footer>
      <div class="author col-xs-8 col-sm-6">
        <%= link_to the_recipe.user do %>
          <% if the_recipe.user.img_upload.url %>
          <div class="profile-img" style="background-image:url('<%= the_recipe.user.img_upload.url %>')">
           </div>
          <% else %>
            <span class="glyphicon glyphicon-user"></span>
        <% end %>
          <span class="username"><%= the_recipe.user.first_name %></span>
        <% end %>
      </div>

      <div class="meta col-xs-4 col-sm-6">
        <span class="reviews"><span class="glyphicon glyphicon-comment" aria-hidden="true"></span><%= the_recipe.reviews.count %></span>
        <div class="favorites">
          <%= link_to favorite_path(id: the_recipe.id), method: :post do %>
          <div class="favorite-btn" recipe_id="<%= the_recipe.id %>">
            <span class="<%= the_recipe.heart_class(current_user) %>"></span>
            <span class="count"><%= the_recipe.favorites_count(current_user) %></span>
            </div>
          <% end %>
        </div>
    </footer>

  </div>
</div>

app/views/recipes/_render_recipes.html.erb
<% if @recipes && !@recipes.empty? %>
  <h2 class="search-msg"><%= @search_msg %></h2>
  <% @recipes.each do |recipe| %>
    <%= render partial: "recipes/recipe_teaser", locals: {the_recipe: recipe} %>
  <% end %>  
<% else %>
  <h1>No Recipes Found</h1>
<% end %>

app/views/recipes/edit.html.erb
<div class="col-sm-2"></div>
<div class="col-sm-8">
<h1>Edit Recipe</h1>

<%= render 'form' %>
</div>

app/views/recipes/new.html.erb
<div class="col-sm-2"></div>
<div class="col-sm-8">
<h1>New Recipe</h1>

<%= render 'form' %>
</div>

app/views/recipes/show.html.erb
<style>
.glass {
  margin-left: auto;
  margin-right: auto;
  height: <%= [50 * @recipe.amounts.size, 300].max %>px;
  width: <%= ([50 * @recipe.amounts.size, 300].max) / 2 %>px;
}
</style>
<script>
  $(function(){
    function goUp(){
      $('.water')
       .animate({ height: '90%' }, (Math.random() * 1000) + 1000, "easeInOutBack")
       .animate({ height: '95%' }, (Math.random() * 1000) + 1000, "easeInOutBack", goUp);
    }

    goUp();
  })
</script>

<div class="recipe recipe-<%= @recipe.id %> show">
<div class="item-body">
  <header>
    <div class="page-header">
  <h1><%= @recipe.name %></h1>

    <div class="author">
      <%= link_to @recipe.user do %>
        <% if @recipe.user.img_upload.url %>
         <div class="profile-img" style="background-image:url('<%= @recipe.user.img_upload.url %>')"></div>
        <% else %>
        <span class="glyphicon glyphicon-user"></span>
        <% end %>
      <h4 class="username">by <%= @recipe.user.first_name %></h4> <% end %></div>

<div class="item-edit">
  <%  if current_user.nil? %>
  <% elsif @recipe.user.id == current_user.id || current_user.id < 4 %>
    <%= link_to "Edit", edit_recipe_path, class: 'btn btn-default btn-s'%>
    <%= link_to "Delete", recipe_path(@recipe), method: :delete, class: 'btn btn-default btn-s'%>
  <% end %>
</div>




  <div class="meta small">
      <div class="favorites">
        <%= link_to favorite_path(id: @recipe.id), method: :post do %>
        <div class="favorite-btn" recipe_id="<%= @recipe.id %>"><span class="<%= @recipe.heart_class(current_user) %>"></span><span class="count"><%= @recipe.favorites_count(current_user) %></span></div>
        <% end %>
        <div class="favorites-message" recipe_message_id="<%= @recipe.id %>"><%= @recipe.favorites_message(current_user) %></div>
      </div>
        <% if @recipe.reviews.count > 1 %>
          <div class="comments"><span class="glyphicon glyphicon-comment" aria-hidden="true"></span><%= @recipe.reviews.count %> Comments</div>
        <% else  %>
        <div class="comments"><span class="glyphicon glyphicon-comment" aria-hidden="true"></span><%= @recipe.reviews.count %> Comment</div>
        <% end %>
    </div>
      </div>
  <div class="item-img">
    <% if @recipe.img_upload != "" %>
      <%= image_tag @recipe.img_upload.url %>
    <% else %>
      <div class="glass">
        <div class="water">
          <img class="water_top" src="/water_top.png">
          <% @recipe.amounts.each do |x| %>
            <div style="background-color:#<%= "%06x" % (rand * 0xffffff) %>;height:<%= (1 / @recipe.amounts.size.to_f) * 100 %>%"><div style=""><%= x.ingredient.name %></div></div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
  </header>
    <div class="content">
  <h3 class="description"><%= @recipe.description %></h3>
      <div class="ingredients">
        <div class="ing-label">
          <h4>Ingredients</h4>
        </div>
        <ul>
          <% @recipe.amounts.each do |amount| %>
            <li><span class="quantity"><%= amount.quantity %></span> <span class="unit"><%= amount.unit %></span> <span class="ingredient"><%= link_to amount.ingredient.name, ingredient_path(amount.ingredient.name) %></span></li>
          <% end %>
        </ul>
      </div>

      <div class="directions">
        <p><%= simple_format(@recipe.steps) %></p>
      </div>
    </div>

    <div class="rec-meta">
    <h5><span class="glyphicon glyphicon-signal" aria-hidden="true"></span> Difficulty <span class="count"><%= @recipe.difficulty %></span></h5>

    <h5><span class="glyphicon glyphicon-glass" aria-hidden="true"></span> Serves <% if @recipe.servings %><span class="count"><%= @recipe.servings %></span><% else %>1<% end %></h5>
  </div>
  <div class="divider"></div>

    <% if @recipe.tags.any? %>
      <div class="item-tags">
      <h5><span class="label-dark">Filed Under: </span>
        <% @recipe.tags.each do |tag| %>
          <span class="btn btn-default btn-sm"><%= link_to tag.name, tag_path(tag.name) %></span>
        <% end %>
      </h5>
      </div>
    <% end %>

<div class="item-comments">
  <h3 class="header">Comments</h3>
      <div id='reviews'>
        <%= render partial: @recipe.reload.reviews %>
      </div>

  <div id="review-form">
    <%= render "reviews/form" %>
  </div>
</div>
</div>
</div>

<% similar_r = @recipe.similar_recipes %>
<% if similar_r.flatten.count > 0 %>
  <div class="item-related">
    <div class="user-recipes">
    <h3 class="header">Related</h3>
    <% if similar_r[0].count > 0 %>
      <% similar_r[0].each do |sim| %>
        <%= render partial: "recipes/recipe_teaser", locals: {the_recipe: sim} %>
      <% end %>
    </div>
    <% end %>
    <% if similar_r[1].count > 0 %>
     <div class="user-recipes">
        <% similar_r[1].each do |sim| %>
          <%= render partial: "recipes/recipe_teaser", locals: {the_recipe: sim} %>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>