config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources 'users'
    resources 'recipes' do
    resources 'reviews'
  end


  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/sort' => 'ajax#get_recipes'
  get '/search' => 'ajax#get_recipes'
  #post '/search' => 'ajax#search'
  get '/tags/:name' => 'tags#show', as: :tag
  get '/ingredients/:name' => 'ingredients#show', as: :ingredient
  post '/recipe/:id/favorite' => 'recipes#favorite', as: :favorite

  get '/age' => 'sessions#age'


end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @review = @recipe.reviews.build(review_params)

    if @review.save
      @new_review = @recipe.reviews.build
      respond_to do |format|
        format.html do
          redirect_to @recipe
        end
        format.js
      end
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @recipe = @review.recipe
    @review.destroy
    respond_to do |format|
      format.html do
        redirect_to @recipe
      end
      format.js
    end

  end

  private

  def review_params
    params.require(:review).permit(:comment, :user_id)
  end

end

app/views/reviews/_form.html.erb
<% if current_user.nil? %>
  <%= link_to 'Create Account', new_user_path, class: "anon" %> or <%= link_to 'Log In',login_path, class: "anon" %> to Comment
<% else %>
  <%= form_for [@recipe, @new_review], remote: true do |f| %>
    <% if signed_in? %>
      <%= f.text_area :comment, rows: '3', placeholder: "Comment here..." %>
      <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.submit 'Leave Comment', class: "btn-primary" %>
    <% end %>
  <% end %>
<% end %>

app/views/reviews/_review.html.erb
<%= div_for review do %>

  <div class="review-comment">
  <div class="author">
      <%= link_to review.user do %>
        <% if review.user.img_upload.url %>
         <div class="profile-img" style="background-image:url('<%= review.user.img_upload.url %>')"></div>
        <% else %>
        <span class="glyphicon glyphicon-user"></span>
        <% end %>
      <h3 class="username"> <%= review.user.first_name %></h3> <% end %><small><%= time_ago_in_words(review.created_at) %> ago</small></div>
      <div class="content"><p><%= review.comment %></p>


  <% if current_user.nil? %>
  <% elsif review.user.id == current_user.id || current_user.id < 4 %>
    <%= link_to 'Delete', recipe_review_path(review.recipe, review), method: :delete, data: { confirm: 'Are you sure?' },
                  id: "#{review.id}_delete", remote: true %><br>
  <% end  %>
<% end %>
  </div></div>

app/views/reviews/create.js.erb
var reviews = $('#reviews');
reviews.append('<%= escape_javascript(render partial: @review) %>');
$('#review_comment').val('')

app/views/reviews/destroy.js.erb
$('#reviews').html('<%= escape_javascript(render partial: @recipe.reviews) %>');